BEGIN;

DROP VIEW IF EXISTS view_probeuser_obu;
DROP VIEW IF EXISTS view_probeuser;

DROP TABLE IF EXISTS ServerLog;
DROP TYPE IF EXISTS AccessType;

DROP TABLE IF EXISTS Probeuser_Obu;
DROP TYPE IF EXISTS PO_Role;
DROP TABLE IF EXISTS ProbeUser;
DROP TABLE IF EXISTS UserProfile;

DROP TABLE IF EXISTS ObuStatus;

DROP TABLE IF EXISTS Obu_has_TestPlan;

DROP TABLE IF EXISTS Obu_has_Config;

DROP TABLE IF EXISTS SysLog;
DROP TABLE IF EXISTS TestLog;

DROP TABLE IF EXISTS Obu;
DROP TYPE IF EXISTS ObuState;

DROP TABLE IF EXISTS TestPlan_has_Setup;
DROP TABLE IF EXISTS Test;
DROP TABLE IF EXISTS TestType;
DROP TABLE IF EXISTS Setup;
DROP TABLE IF EXISTS TestPlan;

DROP TABLE IF EXISTS Config;

DROP TABLE IF EXISTS Hardware;

COMMIT;